### ISSUE TITLE
i can not install basemap-data-hires

### ISSUE THREAD

**Issue by gehongyi** [conda-forge/basemap-data-hires-feedstock#13]
when i install the basemap-data-hires,it shows some errors as following code:

C:\Users\Administrator>conda install -c conda-forge basemap-data-hires
Fetching package metadata ..............

CondaHTTPError: HTTP None None
for url <None>

An HTTP error occurred when trying to retrieve this URL.
ConnectTimeout(MaxRetryError("HTTPSConnectionPool(host='repo.continuum.io', port
=443): Max retries exceeded with url: /pkgs/msys2/noarch/repodata.json.bz2 (Caus
ed by ConnectTimeoutError(<requests.packages.urllib3.connection.VerifiedHTTPSCon
nection object at 0x0000000005922198>, 'Connection to repo.continuum.io timed ou
t. (connect timeout=6.1)'))",),)

i have tried many times , hower the situation always occured,how can i resolve it?thank you

**Comment by ocefpaf** [comment]
I'm away from my laptop to test but it does look like a temporary network
issue. Please try again at a latet time.
